In [1]:
import os
from pathlib import Path
ROOT = "../" # Base directory relative to this notebook's location. Adjust if the notebook is moved
CSV_DIR = os.path.join(ROOT, "csv", "historical-data")

import pandas as pd
from IPython.display import clear_output
import time

import sys
sys.path.append(ROOT)
import src.weather_stats as ws

### Updating stats

In [2]:
rows = []

processed = 0

for filename in os.listdir(CSV_DIR):

    file_path = os.path.join(CSV_DIR, filename)

    # Ignore subfolders
    if not os.path.isfile(file_path):
        continue

    try:
        # Force indicativo as text
        df = pd.read_csv(file_path, dtype={"indicativo": str})

        clear_output(wait=True)
        print(f"Processing {filename}... ({processed + 1}/{len(os.listdir(CSV_DIR))})")
        time.sleep(0.01)

        rows.append(
            {
                "indicativo": str(df["indicativo"].iloc[0]) if "indicativo" in df.columns else None,
                "nombre": df["nombre"].iloc[0] if "nombre" in df.columns else None,
                "altitud": df["altitud"].iloc[0] if "altitud" in df.columns else None,
                "provincia": df["provincia"].iloc[0] if "provincia" in df.columns else None,
                "num_records": len(df),
                "avg_tmin": ws.safe_stat(df, "tmin", lambda s: s.mean()),
                "avg_tmax": ws.safe_stat(df, "tmax", lambda s: s.mean()),
                "avg_prec": ws.safe_stat(df, "prec", lambda s: s.mean()),
                "avg_velmedia": ws.safe_stat(df, "velmedia", lambda s: s.mean()),
                "std_tmed": ws.safe_stat(df, "tmed", lambda s: s.std()),
                "longest_gap_days": ws.calculate_longest_gap_days(df),
            }
        )

        processed += 1

    except Exception as e:
        print(f"Error processing {filename}: {e}")

stations_df = pd.DataFrame(rows)

# Ensure consistent type before sorting
stations_df["indicativo"] = stations_df["indicativo"].astype(str)

stations_df = (
    stations_df
    .sort_values("indicativo")
    .reset_index(drop=True)
)

print(f"Processed {len(stations_df)} stations.")
display(stations_df.head())

Processing C939T_hist.csv... (775/778)
Processed 775 stations.

,indicativo,nombre,altitud,provincia,num_records,avg_tmin,avg_tmax,avg_prec,avg_velmedia,std_tmed,longest_gap_days
0,0009X,ALFORJA,406,TARRAGONA,1760,10.326706,21.866588,1.275278,2.997434,6.333601,19
1,0016A,REUS AEROPUERTO,71,TARRAGONA,1950,11.727940,22.801129,1.312099,3.569625,6.325506,1
2,0034X,VALLS,233,TARRAGONA,1950,10.850077,22.453155,1.128718,NaN,6.341960,1
3,0042Y,TARRAGONA,55,TARRAGONA,1934,13.167755,22.431363,1.341408,NaN,5.705496,10
4,0061X,PONTONS,632,BARCELONA,1911,8.404505,19.591200,1.534488,3.449710,6.158788,37

In [4]:
date_cutoff = "2025-12-31"  # Set to None to include all dates

rows = []
processed = 0

for filename in os.listdir(CSV_DIR):
    file_path = os.path.join(CSV_DIR, filename)

    # Ignore subfolders
    if not os.path.isfile(file_path):
        continue

    try:
        # Force indicativo as text
        df = pd.read_csv(file_path, dtype={"indicativo": str})

        # Parse fecha to datetime (coerce invalid -> NaT)
        if "fecha" in df.columns:
            df["fecha"] = pd.to_datetime(df["fecha"], errors="coerce")

        # Filter by date_cutoff if provided
        if date_cutoff is not None and "fecha" in df.columns:
            cutoff_dt = pd.to_datetime(date_cutoff)
            df = df[df["fecha"].notna() & (df["fecha"] <= cutoff_dt)]

        # Skip files with no rows after filtering
        if df.empty:
            clear_output(wait=True)
            print(f"Skipping {filename}: no rows after date filter")
            processed += 1
            time.sleep(0.005)
            continue

        clear_output(wait=True)
        print(f"Processing {filename}... ({processed + 1}/{len(os.listdir(CSV_DIR))})")
        time.sleep(0.01)

        rows.append(
            {
                "indicativo": str(df["indicativo"].iloc[0]) if "indicativo" in df.columns else None,
                "nombre": df["nombre"].iloc[0] if "nombre" in df.columns else None,
                "altitud": df["altitud"].iloc[0] if "altitud" in df.columns else None,
                "provincia": df["provincia"].iloc[0] if "provincia" in df.columns else None,
                "num_records": len(df),
                "avg_tmin": ws.safe_stat(df, "tmin", lambda s: s.mean()),
                "avg_tmax": ws.safe_stat(df, "tmax", lambda s: s.mean()),
                "avg_prec": ws.safe_stat(df, "prec", lambda s: s.mean()),
                "avg_velmedia": ws.safe_stat(df, "velmedia", lambda s: s.mean()),
                "std_tmed": ws.safe_stat(df, "tmed", lambda s: s.std()),
                "longest_gap_days": ws.calculate_longest_gap_days(df),
            }
        )

        processed += 1

    except Exception as e:
        print(f"Error processing {filename}: {e}")

stations_df = pd.DataFrame(rows)

# Ensure consistent type before sorting
stations_df["indicativo"] = stations_df["indicativo"].astype(str)

stations_df = (
    stations_df
    .sort_values("indicativo")
    .reset_index(drop=True)
)

print(f"Processed {len(stations_df)} stations.")
display(stations_df.head())

Processing C939T_hist.csv... (775/778)
Processed 775 stations.

,indicativo,nombre,altitud,provincia,num_records,avg_tmin,avg_tmax,avg_prec,avg_velmedia,std_tmed,longest_gap_days
0,0009X,ALFORJA,406,TARRAGONA,1760,10.326706,21.866588,1.275278,2.997434,6.333601,19
1,0016A,REUS AEROPUERTO,71,TARRAGONA,1826,11.984805,23.079660,1.282667,3.531507,6.397225,1
2,0034X,VALLS,233,TARRAGONA,1826,11.130849,22.759068,1.093428,NaN,6.391482,1
3,0042Y,TARRAGONA,55,TARRAGONA,1810,13.478073,22.727741,1.315155,NaN,5.729166,10
4,0061X,PONTONS,632,BARCELONA,1787,8.673445,19.903417,1.458843,3.397972,6.185819,37

In [3]:
stations_df.to_csv(os.path.join(ROOT, "csv", "stats", "weather-station-stats.csv"), index=False)

### Loading stats

In [65]:
stations_df = pd.read_csv(os.path.join(ROOT, "csv", "stats", "weather-station-stats.csv"))

### Descriptive analysis and validations

Highest Average High Temperature

In [5]:
# Highest Average High Temperature
highest_tmax = stations_df.sort_values("avg_tmax", ascending=False).head(15)
display(
    highest_tmax.style
    .set_properties(subset=["avg_tmax"], **{"background-color": "#ff9999", "color": "black"})
)

Lowest Average High Temperature

In [7]:
# Lowest Average High Temperature
lowest_tmax = stations_df.sort_values("avg_tmax", ascending=True).head(15)
display(lowest_tmax.style.set_properties(subset=["avg_tmax"], **{"background-color": "#829cd4", "color": "black"}))

Highest Average Low Temperature

In [8]:
# Highest Average Low Temperature
highest_tmin = stations_df.sort_values("avg_tmin", ascending=False).head(15)

display(
    highest_tmin.style
    .set_properties(subset=["avg_tmin"], **{"background-color": "#f07d12", "color": "black"})
)

Highest Average Low Temperature excluding Canary Islands

In [9]:
# Highest Average Low Temperature excluding Canary Islands
highest_tmin_no_canary = stations_df[~stations_df["provincia"].str.contains("TENERIFE|PALMAS", na=False)] \
    .sort_values("avg_tmin", ascending=False).head(15)
display(highest_tmin_no_canary.style.set_properties(subset=["avg_tmin"], **{"background-color": "#f07d12", "color": "black"}))

Lowest Average Low Temperature

In [10]:
# Lowest Average Low Temperature
lowest_tmin = stations_df.sort_values("avg_tmin", ascending=True).head(15)
display(lowest_tmin.style.set_properties(subset=["avg_tmin"], **{"background-color": "#cacbf1", "color": "black"}))

Highest Average Precipitation

In [11]:
# Highest Average Precipitation
highest_prec = stations_df.sort_values("avg_prec", ascending=False).head(15)
display(
    highest_prec.style
    .set_properties(subset=["avg_prec"], **{"background-color": "#a1cfff", "color": "black"})
)

Lowest average precipitation

In [12]:
# Lowest Avg Precipitation
lowest_prec = (stations_df.dropna(subset=["avg_prec"]).sort_values("avg_prec", ascending=True).head(15))

display(
    lowest_prec.style
    .set_properties(subset=["avg_prec"], **{"background-color": "#e2d40e", "color": "black"})
)

Lowest average precipitation excluding Canary Islands

In [13]:
# Lowest average precipitation excluding Canary Islands
lowest_prec_no_canary = (
    stations_df[~stations_df["provincia"].str.contains("TENERIFE|PALMAS", na=False)]
    .dropna(subset=["avg_prec"])
    .sort_values("avg_prec", ascending=True)
    .head(15)
)
display(
    lowest_prec_no_canary.style.set_properties(subset=["avg_prec"], **{"background-color": "#e2d40e", "color": "black"})
)

Highest average wind speed

In [14]:
# Highest average wind speed
highest_wind = stations_df.sort_values("avg_velmedia", ascending=False).head(15)
display(
    highest_wind.style
    .set_properties(subset=["avg_velmedia"], **{"background-color": "#ff99f7", "color": "black"})
)

Highest average wind speed excluding Canary Islands

In [15]:
# Highest average wind speed excluding Canary Islands
highest_wind_no_canary = stations_df[~stations_df["provincia"].str.contains("TENERIFE|PALMAS", na=False)] \
    .sort_values("avg_velmedia", ascending=False).head(15)
display(
    highest_wind_no_canary.style
    .set_properties(subset=["avg_velmedia"], **{"background-color": "#ff99f7", "color": "black"})
)

Lowest average wind speed

In [16]:
# Lowest average wind speed
lowest_wind = (
    stations_df.dropna(subset=["avg_velmedia"])
    .sort_values("avg_velmedia", ascending=True)
    .head(15)
)
display(
    lowest_wind.style
    .set_properties(subset=["avg_velmedia"], **{"background-color": "#99ff99", "color": "black"})
)

Highest Temperature Variability (std of tmed)

In [17]:
# Highest Temperature Variability (std of tmed)
highest_variability = stations_df.sort_values("std_tmed", ascending=False).head(15)
display(
    highest_variability.style
    .set_properties(subset=["std_tmed"], **{"background-color": "#c80dda", "color": "black"})
)

Lowest Temperature Variability (std of tmed)

In [18]:
# Lowest Temperature Variability (std of tmed)
lowest_variability = (
    stations_df.dropna(subset=["std_tmed"])
    .sort_values("std_tmed", ascending=True)
    .head(15)
)
display(
    lowest_variability.style.set_properties(subset=["std_tmed"], **{"background-color": "#cbb0cc", "color": "black"})
)

Lowest temperature variability excluding Canary Islands

In [19]:
# Lowest temperature variability excluding Canary Islands
lowest_variability_no_canary = (
    stations_df[~stations_df["provincia"].str.contains("TENERIFE|PALMAS", na=False)]
    .dropna(subset=["std_tmed"])
    .sort_values("std_tmed", ascending=True)
    .head(15)
)
display(
    lowest_variability_no_canary.style.set_properties(subset=["std_tmed"], **{"background-color": "#cbb0cc", "color": "black"})
)

Highest daily temperature range (avg_tmax - avg_tmin)

In [20]:
# Highest daily temperature range (avg_tmax - avg_tmin)
stations_df["avg_temp_range"] = stations_df["avg_tmax"] - stations_df["avg_tmin"]
highest_temp_range = stations_df.sort_values("avg_temp_range", ascending=False).head(15)
display(
    highest_temp_range.style
    .set_properties(subset=["avg_temp_range"], **{"background-color": "#e9430c", "color": "black"})
)

Lowest daily temperature range (avg_tmax - avg_tmin)

In [21]:
# Lowest daily temperature range (avg_tmax - avg_tmin)
lowest_temp_range = (
    stations_df.dropna(subset=["avg_temp_range"])
    .sort_values("avg_temp_range", ascending=True)
    .head(15)
)
display(
    lowest_temp_range.style.set_properties(subset=["avg_temp_range"], **{"background-color": "#99e699", "color": "black"})
)

Lowest daily temperature range (avg_tmax - avg_tmin) excluding Canary Islands

In [22]:
# Lowest daily temperature range (avg_tmax - avg_tmin) excluding Canary Islands
lowest_temp_range_no_canary = (
    stations_df[~stations_df["provincia"].str.contains("TENERIFE|PALMAS", na=False)]
    .dropna(subset=["avg_temp_range"])
    .sort_values("avg_temp_range", ascending=True)
    .head(15)
)
display(
    lowest_temp_range_no_canary.style.set_properties(subset=["avg_temp_range"], **{"background-color": "#99e699", "color": "black"})
)